spring.datasource.url=jdbc:postgresql://localhost:5432/comicdb
spring.datasource.username=postgres
spring.datasource.password=Jasper.0998

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Error detail
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# Suppress open-in-view warning
spring.jpa.open-in-view=false